language: generic
sudo: required

services:
  - docker

install:
  - ./start-easyminer.sh 

script:
  - ./run-tests.sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_68db912d2592_key -iv $encrypted_68db912d2592_iv -in ./deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: ./export-results-to-gh-pages.sh
  on:
    branch: master