language: generic
sudo: required

services:
  - docker

install:
  - ./start-easyminer.sh 

script:
  - ./run-tests.sh

after_success:
  - ./export-results-to-gh-pages.sh

after_failure:
  - ./export-results-to-gh-pages.sh