language: generic
sudo: false
git:
  submodules: false

before_install:
  - git clone -b $TRAVIS_BRANCH --single-branch https://github.com/KIZI/EasyMiner-Tests.git $TRAVIS_BRANCH
  - cd $TRAVIS_BRANCH

services:
  - docker

install:
  - ./start-easyminer.sh 

script:
  - ./run-tests.sh

after_script:
  - openssl aes-256-cbc -K $encrypted_321c4c28b3f1_key -iv  $encrypted_321c4c28b3f1_iv -in ./DeploymentKeys/deploy_key_tests.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
  - ./export-results-to-gh-pages.sh