language: generic
sudo: required

services:
  - docker
before_install:
- openssl aes-256-cbc -K $encrypted_68db912d2592_key -iv $encrypted_68db912d2592_iv
  -in ./deploy_key.enc -out ./deploy_key -d
 - echo -e "Host github.com\n  IdentityFile ./deploy_key" > ~/.ssh/config
 - rm ./deploy.key
 - echo "github.com ssh-rsa $PBKEY" > ~/.ssh/known_hosts
install:
  - ./start-easyminer.sh 

script:
  - ./run-tests.sh

after_success:
  - ./export-results-to-gh-pages.sh

after_failure:
  - ./export-results-to-gh-pages.sh