language: generic
sudo: false

services:
  - docker

install:
  - ./start-easyminer-stable.sh 

script:
  - ./run-tests.sh

after_script:
  - openssl aes-256-cbc -K $encrypted_68db912d2592_key -iv $encrypted_68db912d2592_iv -in ./deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
  - ./export-results-to-gh-pages.sh